timeout: 120
service:
  externalPort: 3000
  internalPort: 3000
image:
  secrets:
  - name: skdigital-bonet-registry
application.migrateCommand: ["bundle", "exec", "rails", "db:migrate"]
ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
livenessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 5
  probeType: "httpGet"
  path: "/up"
readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 10
  probeType: "httpGet"
  path: "/up"
resources:
  requests:
    memory: 2Gi
  limits:
    memory: 3Gi
persistence:
  enabled: true
  volumes:
  - name: autogram-server-storage
    mount:
      path: /app/storage
    claim:
      accessMode: ReadWriteMany
      size: 1Gi
      storageClass: nfs-client
  - name: autogram-server-well-known
    mount:
      path: /app/public/.well-known
    claim:
      accessMode: ReadWriteMany
      size: 1Mi
      storageClass: nfs-client
